### ISSUE TITLE
New version says it's no longer compatible.

### ISSUE THREAD

**Issue by Blossom5280** [Lake1059/ResetTerrainFeatures_NET6#10]
i tried to launch the new version and like i said it said it's incompatible.

im on v 1.6.8.

**Comment by MrMagoozor** [comment]
Same issue

**Comment by Quasi-Detective** [comment]
Can confirm. Previous version works. New one makes SMAPI nag about it "no longer [being] compatible" and not load it.

**Comment by Lake1059** [comment]
Available for download now for game versions 1.6.0-1.6.8.
