### ISSUE TITLE
UI Not Centered, Must Adjust UI Scale to View All Options

### ISSUE THREAD

**Issue by dr-nut** [Lake1059/ResetTerrainFeatures_NET6#5]
Hi there, I just installed Reset Terrain Features on v1.0.3-unofficial.2-Lake1059. When I launch the RTF interface, the UI shows up in the lower right of my screen. At UI scale 95%, the RTF interface's "reset," "clear," and "generate" buttons are covered. I had to hop down to 80% to view the buttons. My resolution is 1920 x 1080 on a 15.6" screen.

I have edited the config file to launch the RTF interface with "R," as I also use the mod To-Dew, which uses L as its interface hotkey.

**Comment by Lake1059** [comment]
I am not the original author of this mod, and I do not know C#, so I cannot make a fix for this issue.
