### ISSUE TITLE
Feature Request: option to exclude player farm from "reset all locations" toggle

### ISSUE THREAD

**Issue by jrandell101** [Lake1059/ResetTerrainFeatures_NET6#7]
If possible, it would be useful to have an option in the menu be able to reset every other terrain in the world in one click without resetting the farm, rather than choose between losing farm progress or physically going to each outdoor location to perform independent resets.

**Comment by Lake1059** [comment]
I am not the original author of this mod, and I do not understand the code logic, so I cannot make the changes to it.
