### ISSUE TITLE
Menu not showing up properly

### ISSUE THREAD

**Issue by stopmakingmesignup** [Lake1059/ResetTerrainFeatures_NET6#8]
Although I'm on full screen, the reset window keeps going out of bounds. I can select everything just fine, but I cannot actually reset the terrain because the buttons are too far below. I'm not sure what else to really say.
![image](https://github.com/user-attachments/assets/ef6bc70c-56f8-450d-a11c-033f8c856d37)

**Comment by Lake1059** [comment]
This is a design problem of the original author. The new version of the game has changed the zoom layer, which causes the interface using the old positioning logic to be misaligned.
The decompiled code is not suitable for making these improvements. You can only try to keep the UI scaling and the game field of view scaling consistent or close.
