### ISSUE TITLE
SMAPI任然不能正确识别

### ISSUE THREAD

**Issue by dune-engineer** [Lake1059/ResetTerrainFeatures_NET6#9]
[SMAPI]    Skipped mods
[SMAPI]    --------------------------------------------------
[SMAPI]       These mods could not be added to your game.
[SMAPI]       - ResetTerrainFeatures_NET6-master\ResetTerrainFeatures_NET6-master because it contains files, but none of them are manifest.json.

**Comment by Bush-cat** [comment]
you downloaded the github repo, you need to download the compiled mod from the releases

**Comment by Bush-cat** [comment]
You can get it here under Assets
https://github.com/Lake1059/ResetTerrainFeatures_NET6/releases
